export const architectureRows = [
  {
    code: "A",
    name: "Pure vision agent",
    summary:
      "LLM looks at screenshots of Creation Kit and emits mouse/keyboard events. No semantic tools.",
    robustness: 2,
    security: 3,
    complexity: 4,
    maintainability: 2,
    licenseFit: 8,
    performance: 2,
    automation: 3,
    testability: 2,
    compatibility: 3,
    externalDeps: 4,
    corruptionRisk: 2,
    weightedScore: 30,
    recommended: false,
    notes:
      "DESCARTADO as primary. DPI, localization, modal dialogs, and hallucinated clicks make this the fastest path to a corrupted plugin. Keep only as a documented last-resort idea, never as MVP.",
  },
  {
    code: "B",
    name: "Windows UI Automation of CK",
    summary:
      "Structured tools drive CK through UIA/MSAA: window titles, AutomationId, control names. No coordinates.",
    robustness: 4,
    security: 5,
    complexity: 5,
    maintainability: 4,
    licenseFit: 8,
    performance: 4,
    automation: 5,
    testability: 4,
    compatibility: 4,
    externalDeps: 5,
    corruptionRisk: 4,
    weightedScore: 47,
    recommended: false,
    notes:
      "Viable only after Inspect.exe proves useful controls. CK dialogs, Render Window, and owner-drawn lists may be opaque. Useful as a narrow fallback, not a platform.",
  },
  {
    code: "C",
    name: "In-process CKPE plugin bridge",
    summary:
      "C++ DLL loaded by CKPE talks JSON-RPC to a local agent and calls reverse-engineered EditorAPI.",
    robustness: 6,
    security: 3,
    complexity: 3,
    maintainability: 3,
    licenseFit: 2,
    performance: 8,
    automation: 7,
    testability: 3,
    compatibility: 3,
    externalDeps: 3,
    corruptionRisk: 3,
    weightedScore: 39,
    recommended: false,
    notes:
      "Highest ceiling for true CK operations, and the worst legal/security profile today. QueryInterface is empty. Requires RE skills the EULA forbids. Research track only.",
  },
  {
    code: "D",
    name: "Headless-first (Mutagen / esper / Papyrus / xEdit)",
    summary:
      "Never open CK unless a capability matrix says the operation is CK-exclusive. Typed plans write candidate plugins.",
    robustness: 9,
    security: 8,
    complexity: 7,
    maintainability: 8,
    licenseFit: 5,
    performance: 9,
    automation: 8,
    testability: 9,
    compatibility: 7,
    externalDeps: 6,
    corruptionRisk: 8,
    weightedScore: 82,
    recommended: false,
    notes:
      "Best isolated architecture. Already proven by houseCARL and Synthesis. Incomplete for FaceGen, navmesh, lip gen, Render Window. Mutagen GPL is the main license cost.",
  },
  {
    code: "E",
    name: "Hybrid orchestrator (recommended)",
    summary:
      "Planner emits typed operations. Router selects Mutagen/esper, PapyrusCompiler, allowlisted xEdit, and only then CK (worker or UIA). HITL + candidate workspace on every write.",
    robustness: 8,
    security: 8,
    complexity: 5,
    maintainability: 7,
    licenseFit: 5,
    performance: 8,
    automation: 8,
    testability: 8,
    compatibility: 8,
    externalDeps: 5,
    corruptionRisk: 8,
    weightedScore: 74,
    recommended: true,
    notes:
      "Numeric score is slightly below pure D because of orchestrator complexity. E is still the recommendation: D is the primary backend inside E, and E is the only option that can later absorb CK-exclusive work without pretending headless coverage is complete.",
  },
];

export const SCORE_WEIGHTS = {
  robustness: 15,
  security: 15,
  testability: 12,
  corruptionRisk: 12,
  maintainability: 10,
  licenseFit: 10,
  automation: 8,
  compatibility: 6,
  performance: 5,
  complexity: 4,
  externalDeps: 3,
} as const;
