export const capabilityRows = [
  {
    name: "Read plugin header / masters / hashes",
    mvpClass: "MVP",
    status: "Research — backend exists",
    backend: "Mutagen or TES4 parser",
    risk: "Low",
    notes: "Do not require CK. Do not commit real game plugins as fixtures.",
  },
  {
    name: "List records / find by EditorID",
    mvpClass: "MVP",
    status: "Research — backend exists",
    backend: "Mutagen overlay",
    risk: "Low",
    notes: "Prefer EditorID over raw FormID for agent plans.",
  },
  {
    name: "Create miscellaneous item",
    mvpClass: "MVP candidate",
    status: "Research — backend exists",
    backend: "Mutagen write",
    risk: "Low",
    notes: "Smallest honest write PoC after header I/O.",
  },
  {
    name: "Create actor base",
    mvpClass: "V1",
    status: "Research — backend exists; FaceGen does not",
    backend: "Mutagen write; CK for FaceGen",
    risk: "Medium",
    notes: "A plugin can contain an NPC_ that still looks grey in-game without FaceGeom.",
  },
  {
    name: "Create quest / stages",
    mvpClass: "Not MVP",
    status: "Experimental in other projects",
    backend: "Mutagen / esper",
    risk: "High",
    notes: "SkyrimCK-MCP and houseCARL show data-layer quests are possible. Semantic correctness is not implied.",
  },
  {
    name: "Compile Papyrus",
    mvpClass: "V1",
    status: "Research — CLI exists",
    backend: "Official PapyrusCompiler.exe",
    risk: "Low",
    notes: "Timeouts, explicit -i/-o/-f, reject stale PEX.",
  },
  {
    name: "Validate plugin (static)",
    mvpClass: "MVP",
    status: "Research — backend exists",
    backend: "xEdit check-for-errors / Mutagen analyzers",
    risk: "Low",
    notes: "Static pass ≠ in-game behavior.",
  },
  {
    name: "CK window inspect",
    mvpClass: "Milestone 1",
    status: "NO VERIFICADO",
    backend: "UIA / Inspect.exe",
    risk: "Medium",
    notes: "POC-001. Read-only.",
  },
  {
    name: "CK UI write",
    mvpClass: "Only if headless cannot",
    status: "Unsupported until POC-001",
    backend: "UIA fallback",
    risk: "High",
    notes: "Coordinate clicks are forbidden.",
  },
  {
    name: "CKPE in-process bridge",
    mvpClass: "Long-term research",
    status: "BLOQUEADO pending legal review",
    backend: "CKPE PluginAPI",
    risk: "Critical",
    notes: "QueryInterface empty. EULA reverse-engineering conflict.",
  },
  {
    name: "Render Window",
    mvpClass: "Out of scope",
    status: "Unsupported",
    backend: "CK GUI",
    risk: "Critical",
    notes: "No headless equivalent.",
  },
  {
    name: "Navmesh",
    mvpClass: "Out of scope",
    status: "Unsupported",
    backend: "CK GUI",
    risk: "Critical",
    notes: "Do not automate. Corruption and pathing risk.",
  },
  {
    name: "Worldspace / landscape",
    mvpClass: "Out of scope",
    status: "Unsupported",
    backend: "CK GUI",
    risk: "Critical",
    notes: "Stop criterion: do not implement.",
  },
];
