export const nameRows = [
  {
    name: "Formfoundry",
    memorability: "High — concrete metaphor, two common words",
    skyrimRelation: "Indirect (FormID / foundry). No official term.",
    ckRelation: "Weak-moderate. Speaks to records, not the editor.",
    searchability: "Low collision in this pass. Not a Bethesda mark.",
    collisions:
      "No GitHub/Nexus/PyPI hit for the exact compound in this search. Still needs a trademark screen before any release.",
    length: "11 letters, 3 syllables",
    pronunciation: "Clear",
    visualIdentity: "Anvil + type/form marks, copper/ink. Easy to illustrate without using the imperial dragon.",
    trademarkRisk: "Lower than lore names. Not zero.",
    recommendation: "Leading candidate. Do not register anything yet.",
  },
  {
    name: "Anvilwright",
    memorability: "High",
    skyrimRelation: "Anvils exist in-world. Risk of sounding like a crafting mod.",
    ckRelation: "Craftsman metaphor, not CK-specific.",
    searchability: "No exact project hit. 'Anvil' is a crowded word (Anvil app server on PyPI).",
    collisions: "anvil-app-server on PyPI. Many 'Anvil' products.",
    length: "11 letters",
    pronunciation: "Clear",
    visualIdentity: "Strong, but easy to look like a smithing mod.",
    trademarkRisk: "Medium because Anvil is crowded.",
    recommendation: "Backup. Prefer Formfoundry to avoid Anvil collisions.",
  },
  {
    name: "Recordloom",
    memorability: "Moderate",
    skyrimRelation: "None. Good.",
    ckRelation: "Record-centric, accurate.",
    searchability: "Likely clean.",
    collisions: "None found in this pass.",
    length: "10 letters",
    pronunciation: "Clear",
    visualIdentity: "Textile/loom — less martial, more systematic.",
    trademarkRisk: "Low-medium",
    recommendation: "Viable if Formfoundry collides later.",
  },
  {
    name: "Pluginwright",
    memorability: "Moderate",
    skyrimRelation: "None.",
    ckRelation: "Accurate but generic across all game engines.",
    searchability: "Generic SEO.",
    collisions: "Unlikely exact. 'Plugin' is noisy.",
    length: "12 letters",
    pronunciation: "Clear",
    visualIdentity: "Flat.",
    trademarkRisk: "Low",
    recommendation: "Descriptive subtitle, not a product name.",
  },
  {
    name: "Vestige Lab",
    memorability: "Moderate",
    skyrimRelation: "Vestige is ESO player-character lore. Too close to Bethesda IP flavor.",
    ckRelation: "None.",
    searchability: "ESO will dominate search.",
    collisions: "ESO 'Vestige' is ubiquitous.",
    length: "Two words",
    pronunciation: "Clear",
    visualIdentity: "Too Elder Scrolls.",
    trademarkRisk: "Avoid — looks fan-official.",
    recommendation: "DESCARTADO for affiliation risk.",
  },
  {
    name: "Sky-Claw / SkyClaw / SkyrimForge / houseCARL",
    memorability: "High — and already taken",
    skyrimRelation: "Direct or existing products.",
    ckRelation: "Existing tools.",
    searchability: "Collides hard.",
    collisions:
      "SkyworkAI/skyclaw; SkyrimForge (ShugokiFable); houseCARL (Avick3110). Do not reuse.",
    length: "n/a",
    pronunciation: "n/a",
    visualIdentity: "n/a",
    trademarkRisk: "Collision, not just trademark.",
    recommendation: "DESCARTADO. Also do not imply affiliation with Bethesda, Nexus, Steam, or those tools.",
  },
];
