export const useCaseRows = [
  {
    name: "Open plugin",
    description: "Load an ESP/ESM/ESL for inspection without saving.",
    mvpInclusion: "MVP adjacent",
    riskLevel: "Low",
    preferredBackend: "Mutagen overlay / xEdit -quickedit",
  },
  {
    name: "Inspect plugin header",
    description: "Read masters, flags, header version, author, description, hashes.",
    mvpInclusion: "MVP",
    riskLevel: "Low",
    preferredBackend: "Mutagen / custom TES4 parser",
  },
  {
    name: "List / find forms by EditorID",
    description: "Locate records without depending on FormID indices.",
    mvpInclusion: "MVP",
    riskLevel: "Low",
    preferredBackend: "Mutagen LinkCache / record walk",
  },
  {
    name: "Create item (MISC)",
    description: "Create a minimal typed miscellaneous item on a candidate plugin.",
    mvpInclusion: "MVP candidate",
    riskLevel: "Low",
    preferredBackend: "Mutagen write",
  },
  {
    name: "Create actor (NPC_)",
    description: "Create a base actor with race, name, and EditorID.",
    mvpInclusion: "V1",
    riskLevel: "Medium",
    preferredBackend: "Mutagen write; FaceGen still requires CK",
  },
  {
    name: "Create weapon / armor / spell",
    description: "Typed combat records with keywords, enchantments, and models.",
    mvpInclusion: "V1",
    riskLevel: "Medium",
    preferredBackend: "Mutagen write",
  },
  {
    name: "Create recipe / constructed object",
    description: "COBJ records for smithing or alchemy.",
    mvpInclusion: "V1",
    riskLevel: "Low",
    preferredBackend: "Mutagen write",
  },
  {
    name: "Create / edit leveled lists",
    description: "LVLI / LVLN / LVSP mutations. Easy to break loot balance.",
    mvpInclusion: "V1",
    riskLevel: "Medium",
    preferredBackend: "Mutagen write + conflict report",
  },
  {
    name: "Create quest + stages",
    description: "QUST with stages, log entries, and flags.",
    mvpInclusion: "V1 / later",
    riskLevel: "High",
    preferredBackend: "Mutagen or esper; validate with xEdit and in-game",
  },
  {
    name: "Create aliases",
    description: "Quest aliases, fill types, and conditions.",
    mvpInclusion: "Not MVP",
    riskLevel: "High",
    preferredBackend: "Headless possible; semantic correctness unverified",
  },
  {
    name: "Create dialogue",
    description: "DIAL / INFO / branch graphs, SEQ files, voice hooks.",
    mvpInclusion: "Not MVP",
    riskLevel: "High",
    preferredBackend: "houseCARL already does a data-layer version; CK still needed for some voice/lip work",
  },
  {
    name: "Create AI package",
    description: "PACK templates and conditions.",
    mvpInclusion: "Not MVP",
    riskLevel: "Medium",
    preferredBackend: "esper/Mutagen; SkyrimCK-MCP already authors Travel packages",
  },
  {
    name: "Compile Papyrus",
    description: "psc → pex via official compiler.",
    mvpInclusion: "V1",
    riskLevel: "Low",
    preferredBackend: "PapyrusCompiler.exe CLI",
  },
  {
    name: "Attach script / VMAD",
    description: "Bind compiled scripts and properties to records.",
    mvpInclusion: "V1",
    riskLevel: "High",
    preferredBackend: "Mutagen VMAD model; silent None if properties unbound",
  },
  {
    name: "Save candidate plugin",
    description: "Write a new file in workspace/candidates, never overwrite originals.",
    mvpInclusion: "MVP",
    riskLevel: "Medium",
    preferredBackend: "Mutagen WriteToBinary into workspace",
  },
  {
    name: "Create references / place in cell",
    description: "REFR / ACHR placement, persistence, initially disabled.",
    mvpInclusion: "Not MVP",
    riskLevel: "High",
    preferredBackend: "Headless possible; visual placement needs CK Render Window",
  },
  {
    name: "Edit cells / worldspace",
    description: "CELL, WRLD, landscape, precombined implications.",
    mvpInclusion: "Unsupported for automation",
    riskLevel: "Critical",
    preferredBackend: "CK + human",
  },
  {
    name: "Render Window",
    description: "3D editor camera, object placement, lighting preview.",
    mvpInclusion: "Unsupported",
    riskLevel: "Critical",
    preferredBackend: "CK GUI only",
  },
  {
    name: "Navmesh",
    description: "NAVM generation and finalization.",
    mvpInclusion: "Unsupported",
    riskLevel: "Critical",
    preferredBackend: "CK only; do not automate",
  },
  {
    name: "FaceGen / export NPC head",
    description: "Generate FaceGeom / FaceTint assets from an NPC record.",
    mvpInclusion: "Not MVP",
    riskLevel: "High",
    preferredBackend: "CK exclusive in practice",
  },
];
