-- Correct stored licensing content without deleting/reseeding research data.
-- Fresh databases remain empty for seedResearch; only seeded desks receive new rows.
--> statement-breakpoint
UPDATE "research_license_entries" SET "notes" = 'MIT code may be combined with GPL code, but distributing the combined work requires GPL compliance, including corresponding source and notices; MIT alone is insufficient. ADR-003 L3 distribution model still requires legal authorization.' WHERE "component" = 'Mutagen / Synthesis / Spriggit';
--> statement-breakpoint
UPDATE "research_license_entries" SET "license" = 'MIT for material the licensor has authority to license; third-party licenses remain separate.', "risk" = 'Imported research provenance unresolved', "legal_review_required" = true, "distribution_authorization_status" = 'LEGAL_REVIEW_REQUIRED', "notes" = 'The maintainer reports probable AI generation, not verified authorship or third-party permissions. See docs/research/source-manifest.md and /licenses/THIRD_PARTY_NOTICES.md. ADR-003 remains unresolved.' WHERE "component" = 'This research portal (Next.js app)';
--> statement-breakpoint
UPDATE "research_document_sections" SET "body" = replace("body", 'These are not equivalent. Executing the user''s PapyrusCompiler is aligned with how CK itself works. Linking Mutagen makes our worker GPL-3.0. Distributing CreationKit.exe or vanilla .psc is forbidden.', 'These are not equivalent. Executing the user''s PapyrusCompiler remains subject to its EULA. MIT code may be combined with GPL code; distributing a combined Mutagen work requires GPL compliance, including corresponding source and notices, rather than MIT alone. This project forbids bundling CreationKit.exe or vanilla .psc.') WHERE "document_slug" = 'licensing' AND "heading" = 'Three different acts';
--> statement-breakpoint
INSERT INTO "research_license_entries" ("component", "license", "intended_use", "modification", "distribution", "risk", "legal_review_required", "distribution_authorization_status", "notes", "sort_order")
SELECT 'Discovery Desk npm dependencies', 'MIT, Apache-2.0 and other licenses; see exact lockfile inventory.', 'Next.js research portal and development tooling.', 'Subject to each package license.', 'Preserve upstream licenses, copyright and applicable NOTICE files for shipped components.', 'Release contents require review', false, 'LEGAL_REVIEW_REQUIRED', 'docs/research/npm-license-inventory.md includes development and optional packages; it is not an inventory of a shipped artifact.', (SELECT COALESCE(MAX("sort_order"), 0) + 1 FROM "research_license_entries")
WHERE EXISTS (SELECT 1 FROM "research_verdicts")
AND NOT EXISTS (SELECT 1 FROM "research_license_entries" WHERE "component" = 'Discovery Desk npm dependencies');
--> statement-breakpoint
INSERT INTO "research_license_entries" ("component", "license", "intended_use", "modification", "distribution", "risk", "legal_review_required", "distribution_authorization_status", "notes", "sort_order")
SELECT 'sharp / libvips platform packages', 'Apache-2.0 / LGPL-3.0-or-later; combined expressions vary by platform.', 'Optional native image processing dependency of Next.js.', 'Subject to the licenses of the affected code and native libraries.', 'Retain notices; satisfy applicable LGPL source and replacement/relinking requirements.', 'Inspect actual native binaries in each release', false, 'LEGAL_REVIEW_REQUIRED', 'LGPL dependencies do not automatically convert the whole MIT application to GPL. See /licenses/THIRD_PARTY_NOTICES.md.', (SELECT COALESCE(MAX("sort_order"), 0) + 1 FROM "research_license_entries")
WHERE EXISTS (SELECT 1 FROM "research_verdicts")
AND NOT EXISTS (SELECT 1 FROM "research_license_entries" WHERE "component" = 'sharp / libvips platform packages');
--> statement-breakpoint
INSERT INTO "research_license_entries" ("component", "license", "intended_use", "modification", "distribution", "risk", "legal_review_required", "distribution_authorization_status", "notes", "sort_order")
SELECT 'lightningcss / axe-core / caniuse-lite', 'MPL-2.0 (lightningcss, axe-core); CC-BY-4.0 (caniuse-lite).', 'CSS/lint development tooling and browser compatibility data.', 'Observe covered-source, attribution and change-notice conditions as applicable.', 'Review covered code/data actually shipped; generated CSS is not automatically MPL.', 'Do not confuse development dependencies with browser delivery', false, 'LEGAL_REVIEW_REQUIRED', 'Preserve upstream notices and satisfy source/attribution requirements when distributing covered material.', (SELECT COALESCE(MAX("sort_order"), 0) + 1 FROM "research_license_entries")
WHERE EXISTS (SELECT 1 FROM "research_verdicts")
AND NOT EXISTS (SELECT 1 FROM "research_license_entries" WHERE "component" = 'lightningcss / axe-core / caniuse-lite');
--> statement-breakpoint
INSERT INTO "research_license_entries" ("component", "license", "intended_use", "modification", "distribution", "risk", "legal_review_required", "distribution_authorization_status", "notes", "sort_order")
SELECT 'Fraunces / IBM Plex Sans / IBM Plex Mono', 'SIL Open Font License 1.1', 'Fonts downloaded and self-hosted by next/font/google.', 'Subject to OFL terms, including reserved font names where applicable.', 'Include copyright and full OFL texts supplied in public/licenses/ with the fonts.', 'Verify notices against the actual font binaries in a release', false, 'LEGAL_REVIEW_REQUIRED', 'Fraunces Project Authors; IBM Corp. (reserved name Plex). License-text origins/hashes are in /licenses/font-sources.json; font binaries are not pinned by those hashes.', (SELECT COALESCE(MAX("sort_order"), 0) + 1 FROM "research_license_entries")
WHERE EXISTS (SELECT 1 FROM "research_verdicts")
AND NOT EXISTS (SELECT 1 FROM "research_license_entries" WHERE "component" = 'Fraunces / IBM Plex Sans / IBM Plex Mono');
