"""Error taxonomy for POC-IPC-001 — exactly the codes accepted in ADR-002.

No synonyms, no extra codes. Both orchestrator and worker use these constants.
"""

INVALID_REQUEST = "INVALID_REQUEST"
REQUEST_LIMIT_EXCEEDED = "REQUEST_LIMIT_EXCEEDED"
UNSUPPORTED_PROTOCOL_VERSION = "UNSUPPORTED_PROTOCOL_VERSION"
INVALID_JOB_ID = "INVALID_JOB_ID"
INVALID_OPERATION = "INVALID_OPERATION"
POLICY_VIOLATION = "POLICY_VIOLATION"
WORKSPACE_VIOLATION = "WORKSPACE_VIOLATION"
PROCESS_TIMEOUT = "PROCESS_TIMEOUT"
PROCESS_FAILED = "PROCESS_FAILED"
PIPE_WRITE_FAILED = "PIPE_WRITE_FAILED"
OUTPUT_LIMIT_EXCEEDED = "OUTPUT_LIMIT_EXCEEDED"
INVALID_RESPONSE = "INVALID_RESPONSE"
RECEIPT_MISMATCH = "RECEIPT_MISMATCH"
ASSERTION_FAILED = "ASSERTION_FAILED"
INTERNAL_ERROR = "INTERNAL_ERROR"

ALL_CODES = frozenset(
    {
        INVALID_REQUEST,
        REQUEST_LIMIT_EXCEEDED,
        UNSUPPORTED_PROTOCOL_VERSION,
        INVALID_JOB_ID,
        INVALID_OPERATION,
        POLICY_VIOLATION,
        WORKSPACE_VIOLATION,
        PROCESS_TIMEOUT,
        PROCESS_FAILED,
        PIPE_WRITE_FAILED,
        OUTPUT_LIMIT_EXCEEDED,
        INVALID_RESPONSE,
        RECEIPT_MISMATCH,
        ASSERTION_FAILED,
        INTERNAL_ERROR,
    }
)
